server:
  port: 8761 # 1?

spring:
  application:
    name: discovery-service # 2?

eureka:
  client:
    register-with-eureka: false # 3?
    fetch-registry: false  # 4?

# server.port : ?? ??? ??? ???? ??? ??? ????. ?? 8761 ??? ?? ????.
# spring.application.name : Application ??? ??? ? ???, ??? ?? ???? application.name ?? ????.
# eureka.client.register-with-eureka : ?? ??? ?????? ??????? ??? false ? ???? ??.
# eureka.client.fetch-registry : ?? ??? false? ???? ???, ??? ??? ??? ?????? ???? ??.

