server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nowgnas/spring-cloud-msa.git
          search-paths: kafka-practice/env
    rabbitmq:
      host: host.docker.internal
      port: 5672
      username: guest
      password: guest