server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nowgnas/spring-cloud-msa.git
          search-paths: kafka-practice/env