server:
    port: 54412

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    application:
        name: order-service
    kafka:
        consumer:
        bootstrapServers: 172.17.0.2:9092
        group-id: user
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto-offset-reset: earliest
        enable-auto-commit: true

eureka:
    instance:
        instance-id: order-microservice-instance
        leaseExpirationDurationInSeconds: 90
        leaseRenewalIntervalInSeconds: 30

    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
