server:
    port: 54412

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    application:
        name: order-service

eureka:
    instance:
        instance-id: order-microservice-instance

    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
