server:
    port: 7000

spring:
    application:
        name: user-service

eureka:
    instance:
        instance-id: user-microservice-instance

    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
dev:
    message: user dev
