server:
    port: 64412

spring:
    application:
        name: user-service
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

eureka:
    instance:
        instance-id: user-microservice-instance

    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
dev:
    message: user dev message change using rabbitmq
